# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgnewsnapshot.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgNewSnapshot(object):
    def setupUi(self, dlgNewSnapshot):
        dlgNewSnapshot.setObjectName("dlgNewSnapshot")
        dlgNewSnapshot.resize(547, 372)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgNewSnapshot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(dlgNewSnapshot)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cmbConfigs = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConfigs.sizePolicy().hasHeightForWidth())
        self.cmbConfigs.setSizePolicy(sizePolicy)
        self.cmbConfigs.setObjectName("cmbConfigs")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbConfigs)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lneName = QtWidgets.QLineEdit(self.groupBox)
        self.lneName.setObjectName("lneName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lneName)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.optSingle = QtWidgets.QRadioButton(self.groupBox)
        self.optSingle.setChecked(True)
        self.optSingle.setObjectName("optSingle")
        self.horizontalLayout.addWidget(self.optSingle)
        self.optPre = QtWidgets.QRadioButton(self.groupBox)
        self.optPre.setObjectName("optPre")
        self.horizontalLayout.addWidget(self.optPre)
        self.optPost = QtWidgets.QRadioButton(self.groupBox)
        self.optPost.setObjectName("optPost")
        self.horizontalLayout.addWidget(self.optPost)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.lblPaired = QtWidgets.QLabel(self.groupBox)
        self.lblPaired.setObjectName("lblPaired")
        self.horizontalLayout.addWidget(self.lblPaired)
        self.cmbPaired = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPaired.sizePolicy().hasHeightForWidth())
        self.cmbPaired.setSizePolicy(sizePolicy)
        self.cmbPaired.setObjectName("cmbPaired")
        self.horizontalLayout.addWidget(self.cmbPaired)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cmbCleanAlgo = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCleanAlgo.sizePolicy().hasHeightForWidth())
        self.cmbCleanAlgo.setSizePolicy(sizePolicy)
        self.cmbCleanAlgo.setObjectName("cmbCleanAlgo")
        self.cmbCleanAlgo.addItem("")
        self.cmbCleanAlgo.addItem("")
        self.cmbCleanAlgo.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cmbCleanAlgo)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        self.txtCommandDisplay = QtWidgets.QTextBrowser(self.groupBox)
        self.txtCommandDisplay.setObjectName("txtCommandDisplay")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.txtCommandDisplay)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.line_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgNewSnapshot)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(dlgNewSnapshot)
        self.buttonBox.accepted.connect(dlgNewSnapshot.accept)
        self.buttonBox.rejected.connect(dlgNewSnapshot.reject)
        self.optPost.toggled['bool'].connect(self.cmbPaired.setVisible)
        self.optPost.toggled['bool'].connect(self.lblPaired.setVisible)
        QtCore.QMetaObject.connectSlotsByName(dlgNewSnapshot)

    def retranslateUi(self, dlgNewSnapshot):
        _translate = QtCore.QCoreApplication.translate
        dlgNewSnapshot.setWindowTitle(_translate("dlgNewSnapshot", "New Snapshot"))
        self.groupBox.setTitle(_translate("dlgNewSnapshot", "New Snapshot"))
        self.label_8.setText(_translate("dlgNewSnapshot", "Config"))
        self.label.setText(_translate("dlgNewSnapshot", "Snapshot name"))
        self.lneName.setPlaceholderText(_translate("dlgNewSnapshot", "Type a short description about your snapshot"))
        self.label_2.setText(_translate("dlgNewSnapshot", "Type :"))
        self.optSingle.setText(_translate("dlgNewSnapshot", "Single"))
        self.optPre.setText(_translate("dlgNewSnapshot", "Pre"))
        self.optPost.setText(_translate("dlgNewSnapshot", "Pos&t"))
        self.lblPaired.setText(_translate("dlgNewSnapshot", "Paired with :"))
        self.label_5.setText(_translate("dlgNewSnapshot", "Cleanup Algorithm"))
        self.cmbCleanAlgo.setItemText(0, _translate("dlgNewSnapshot", "Number"))
        self.cmbCleanAlgo.setItemText(1, _translate("dlgNewSnapshot", "Timeline"))
        self.cmbCleanAlgo.setItemText(2, _translate("dlgNewSnapshot", "Empty-pre-post"))
        self.label_6.setText(_translate("dlgNewSnapshot", "Command :"))

